backend:
  name: git-gateway

media_folder: "site/static/assets" # Folder where user uploaded files should go
public_folder: "assets"

collections: # A list of collections the CMS should be able to edit
