backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/media
public_folder: /media
collections:
  - name: 'page'
    label: 'Page'
    folder: 'content'
    extension: md
    format: yaml-frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
